<?php

/**
 * This file is part of the Spryker Commerce OS.
 * For full license information, please view the LICENSE file that was distributed with this source code.
 */

declare(strict_types = 1);

namespace PlmbTest\Shared\Example\Example;

use Plmb\Zed\Stock\StockConfig;
use PlmbTest\Shared\Example\ExampleTester;
use Pyz\Zed\Stock\StockConfig as PyzStockConfig;
use Spryker\Zed\Kernel\ClassResolver\Config\BundleConfigResolver;

/**
 * Worked example of testing code in the project's own `Plmb` namespace.
 *
 * Copy this suite's shape for real tests: a `codeception.yml` beside the suite, the actor
 * generated by `codecept build`, and `LocatorHelper` told about BOTH project namespaces.
 *
 * Assertions go through the actor (`$i->assertSame(...)`, from the suite's `Asserts` module),
 * not static `PHPUnit\Framework\Assert::` calls - the sniffer rejects an unused `$i` parameter,
 * and the Cest signature requires it.
 *
 * Run it with:
 *   docker/sdk cli "vendor/bin/codecept run -c tests/PlmbTest/Shared/Example/codeception.yml"
 *
 * ---------------------------------------------------------------------------------------
 * WHAT YOU CANNOT TEST FROM IN HERE - read before adding namespace assertions.
 *
 * `LocatorHelper` OVERWRITES the runtime config with the suite's own YAML:
 *
 *     // vendor/spryker/testify/.../Helper/LocatorHelper.php:169
 *     $this->setConfig(KernelConstants::PROJECT_NAMESPACES, $this->config['projectNamespaces']);
 *
 * So `Config::get(KernelConstants::PROJECT_NAMESPACES)` inside this suite returns the
 * `projectNamespaces: ['Plmb', 'Pyz']` line from THIS suite's codeception.yml - never what
 * `config/Shared/config_default.php` says. An assertion on it is circular: it passes even
 * with `Plmb` completely unregistered in the application config (verified by removing it and
 * re-running - the test still went green).
 *
 * Registration in the app config is covered by booting, not by a unit suite. What IS worth
 * asserting here is everything below: autoload wiring, resolver PRECEDENCE, the inheritance
 * chain, and the override's payload.
 * ---------------------------------------------------------------------------------------
 */
class ProjectNamespaceCest
{
    /**
     * Autoload wiring is real and app-level: composer must map the `Plmb\` prefix to src/Plmb.
     * This is not stubbed by any helper, so it fails if the autoload entry is dropped.
     *
     * @param \PlmbTest\Shared\Example\ExampleTester $i
     *
     * @return void
     */
    public function testComposerAutoloadsTheProjectNamespace(ExampleTester $i): void
    {
        $composer = json_decode((string)file_get_contents(APPLICATION_ROOT_DIR . '/composer.json'), true);

        $i->assertSame(
            'src/Plmb/',
            $composer['autoload']['psr-4']['Plmb\\'] ?? null,
            'composer.json no longer autoloads the Plmb\ namespace from src/Plmb/.',
        );
        $i->assertSame(
            'tests/PlmbTest/',
            $composer['autoload-dev']['psr-4']['PlmbTest\\'] ?? null,
            'composer.json no longer autoloads the PlmbTest\ namespace from tests/PlmbTest/.',
        );
    }

    /**
     * Resolver PRECEDENCE: given both namespaces, the Plmb override must win over the Pyz
     * class it extends. Fails if the Plmb config is deleted, renamed, or moved out of the
     * bundle path the resolver expects.
     *
     * @param \PlmbTest\Shared\Example\ExampleTester $i
     *
     * @return void
     */
    public function testBundleConfigResolvesToThePlmbOverrideRatherThanPyz(ExampleTester $i): void
    {
        $resolvedConfig = (new BundleConfigResolver())->resolve(PyzStockConfig::class);

        $i->assertInstanceOf(
            StockConfig::class,
            $resolvedConfig,
            'The resolver did not pick up Plmb\Zed\Stock\StockConfig.',
        );
    }

    /**
     * The inheritance chain: the override extends the *Pyz* config, not the Spryker one, so
     * inherited project behaviour survives. Extending the core class instead drops it with no
     * error at all - which is exactly why this is worth a test.
     *
     * @param \PlmbTest\Shared\Example\ExampleTester $i
     *
     * @return void
     */
    public function testOverrideExtendsThePyzConfigRatherThanTheCoreOne(ExampleTester $i): void
    {
        $config = new StockConfig();

        $i->assertInstanceOf(PyzStockConfig::class, $config);
        $i->assertTrue(
            method_exists($config, 'isConditionalStockUpdateApplied'),
            'Inherited Pyz behaviour is missing - the override probably extends the core config.',
        );
    }

    /**
     * The payload: this override exists to map warehouses to THIS project's stores. Asserting
     * the store keys catches a store rename that would otherwise surface as missing stock.
     *
     * @param \PlmbTest\Shared\Example\ExampleTester $i
     *
     * @return void
     */
    public function testWarehouseMappingCoversTheProjectStores(ExampleTester $i): void
    {
        $mapping = (new StockConfig())->getStoreToWarehouseMapping();

        $i->assertSame(['PL', 'UA'], array_keys($mapping));

        foreach ($mapping as $store => $warehouses) {
            $i->assertNotEmpty($warehouses, "Store {$store} has no warehouse assigned.");
        }
    }
}
