build:
    image: default-noble
    environment:
        php:
            version: 8.3

        node: 'v18.20'

    dependencies:
        override:
            - true # disable PHP dependency (pecl modules) installation

        before:
            - 'npm cache clean --force'
            - 'rm -rf node_modules'
            - 'npm install'

    tests:
        override:
            - true # disable test execution on scrutinizer

    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
