build:
    environment:
        php:
            version: 8.2
            pecl_extensions:

        node: 'v18.20'

    dependencies:
        before:
            - 'npm cache clean --force'
            - 'rm -rf node_modules'
            - 'npm install'

    tests:
        override:
            - true # disable test execution on scrutinizer

    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
