#!/bin/bash

# Script to uninstall marketplace-specific frontend files from B2B Marketplace
# This will remove all marketplace frontend features and related files
#
# The Merchant Portal build tooling now ships inside spryker/zed-ui rather than living in the
# project, so this script only has to undo what the project itself still declares: the generated
# angular.json and the npm scripts that drive the mp-zed-ui workspace. Everything else — the Angular
# toolchain, the lint and TypeScript configurations, the builder itself — disappears with the
# module when uninstall-marketplace-modules.sh removes it via composer.

set -e

echo "=========================================="
echo "Uninstalling Frontend Marketplace Files"
echo "=========================================="
echo ""

# Files to remove. Regenerated by the mp-zed-ui postinstall hook, which step 2 removes first.
FRONTEND_FILES=(
    "angular.json"
)

echo "Step 1: Removing frontend configuration files..."
for file in "${FRONTEND_FILES[@]}"; do
    if [ -f "$file" ]; then
        echo "  Removing $file..."
        rm -f "$file"
        echo "  ✓ Removed $file"
    else
        echo "  ⚠ File not found: $file (skipping)"
    fi
done
echo "✓ Frontend configuration files removed"
echo ""

echo "Step 2: Cleaning up package.json..."
if [ -f "package.json" ]; then
    cat > /tmp/cleanup_package_json.py << 'PYTHON_SCRIPT'
import json


def cleanup_package_json(file_path):
    """Remove Merchant Portal scripts from package.json"""
    with open(file_path, 'r') as f:
        package_data = json.load(f)

    scripts_removed = 0
    if 'scripts' in package_data:
        scripts_to_remove = [key for key in package_data['scripts'].keys() if key.startswith('mp:')]
        for script in scripts_to_remove:
            del package_data['scripts'][script]
            scripts_removed += 1

        # Also remove postinstall if it drives the Merchant Portal build. The project owned that
        # tooling before ("mp:update:paths"); it now delegates to the mp-zed-ui workspace shipped by
        # spryker/zed-ui, which uninstall-marketplace-modules.sh removes right after this script.
        # Leaving the hook behind makes every later "npm ci" fail on a workspace that is gone.
        postinstall_markers = ('mp:update:paths', 'mp-zed-ui')
        postinstall = package_data['scripts'].get('postinstall', '')
        if any(marker in postinstall for marker in postinstall_markers):
            del package_data['scripts']['postinstall']
            scripts_removed += 1

    with open(file_path, 'w') as f:
        json.dump(package_data, f, indent=4)
        f.write('\n')

    print(f"  ✓ Removed {scripts_removed} Merchant Portal scripts")


if __name__ == '__main__':
    cleanup_package_json('package.json')
PYTHON_SCRIPT

    python3 /tmp/cleanup_package_json.py
    rm /tmp/cleanup_package_json.py
else
    echo "  ⚠ package.json not found (skipping)"
fi
echo "✓ package.json cleaned"
echo ""

echo "Step 3: Updating npm dependencies..."
npm install
echo "✓ Dependencies updated"
echo ""

echo "Step 4: Cleaning npm cache..."
rm -rf node_modules/.cache
echo "✓ Cache cleaned"
echo ""

echo "=========================================="
echo "Frontend Marketplace Uninstallation Complete"
echo "=========================================="
echo ""
echo "Summary:"
echo "  - Removed ${#FRONTEND_FILES[@]} configuration files"
echo "  - Cleaned Merchant Portal scripts from package.json"
echo "  - Updated npm dependencies"
echo "  - Cleaned npm cache"
echo ""
echo "Next steps:"
echo "  1. Review changes"
echo "  2. Make sure composer dependencies are installed (run 'composer install --ignore-platform-req=ext-grpc' if needed)"
echo ""
