<?php

/**
 * This file is part of the Spryker Commerce OS.
 * For full license information, please view the LICENSE file that was distributed with this source code.
 */

declare(strict_types = 1);

namespace Pyz\Zed\ProductBundle\Business\ProductBundle\Cart;

use Generated\Shared\Transfer\CartChangeTransfer;
use Generated\Shared\Transfer\ProductOfferCriteriaTransfer;
use Spryker\Shared\ProductOffer\ProductOfferConfig;
use Spryker\Zed\ProductOffer\Business\ProductOfferFacadeInterface;

/**
 * Bundled items are generated by the ProductBundle module from plain SKUs and therefore carry no product offer.
 * In a marketplace setup this leaves them without a merchant, which hides marketplace payment methods.
 * This expander assigns the bundle merchant's own offer of each bundled SKU to the bundled item.
 */
class BundledItemsProductOfferExpander implements BundledItemsProductOfferExpanderInterface
{
    public function __construct(protected ProductOfferFacadeInterface $productOfferFacade)
    {
    }

    public function expandBundledItemsWithProductOffer(CartChangeTransfer $cartChangeTransfer): CartChangeTransfer
    {
        $merchantReferencesByBundleItemIdentifier = $this->getMerchantReferencesByBundleItemIdentifier($cartChangeTransfer);
        if (!$merchantReferencesByBundleItemIdentifier) {
            return $cartChangeTransfer;
        }

        $bundledItemTransfers = $this->getBundledItemsWithoutProductOffer($cartChangeTransfer, $merchantReferencesByBundleItemIdentifier);
        if (!$bundledItemTransfers) {
            return $cartChangeTransfer;
        }

        $productOfferReferencesByMerchantAndSku = $this->getProductOfferReferencesByMerchantAndSku(
            $bundledItemTransfers,
            $merchantReferencesByBundleItemIdentifier,
        );

        foreach ($bundledItemTransfers as $itemTransfer) {
            $merchantReference = $merchantReferencesByBundleItemIdentifier[$itemTransfer->getRelatedBundleItemIdentifierOrFail()];
            $productOfferReference = $productOfferReferencesByMerchantAndSku[$merchantReference][$itemTransfer->getSkuOrFail()] ?? null;

            if ($productOfferReference === null) {
                continue;
            }

            $itemTransfer
                ->setProductOfferReference($productOfferReference)
                ->setMerchantReference($merchantReference);
        }

        return $cartChangeTransfer;
    }

    /**
     * @return array<string, string>
     */
    protected function getMerchantReferencesByBundleItemIdentifier(CartChangeTransfer $cartChangeTransfer): array
    {
        $merchantReferencesByBundleItemIdentifier = [];
        $quoteTransfer = $cartChangeTransfer->getQuote();
        if ($quoteTransfer === null) {
            return $merchantReferencesByBundleItemIdentifier;
        }

        foreach ($quoteTransfer->getBundleItems() as $bundleItemTransfer) {
            if (!$bundleItemTransfer->getBundleItemIdentifier() || !$bundleItemTransfer->getMerchantReference()) {
                continue;
            }

            $merchantReferencesByBundleItemIdentifier[$bundleItemTransfer->getBundleItemIdentifier()] = $bundleItemTransfer->getMerchantReference();
        }

        return $merchantReferencesByBundleItemIdentifier;
    }

    /**
     * @param array<string, string> $merchantReferencesByBundleItemIdentifier
     *
     * @return list<\Generated\Shared\Transfer\ItemTransfer>
     */
    protected function getBundledItemsWithoutProductOffer(
        CartChangeTransfer $cartChangeTransfer,
        array $merchantReferencesByBundleItemIdentifier,
    ): array {
        $bundledItemTransfers = [];

        foreach ($cartChangeTransfer->getItems() as $itemTransfer) {
            if ($itemTransfer->getProductOfferReference() || !$itemTransfer->getRelatedBundleItemIdentifier()) {
                continue;
            }

            if (!isset($merchantReferencesByBundleItemIdentifier[$itemTransfer->getRelatedBundleItemIdentifier()])) {
                continue;
            }

            $bundledItemTransfers[] = $itemTransfer;
        }

        return $bundledItemTransfers;
    }

    /**
     * @param list<\Generated\Shared\Transfer\ItemTransfer> $bundledItemTransfers
     * @param array<string, string> $merchantReferencesByBundleItemIdentifier
     *
     * @return array<string, array<string, string>>
     */
    protected function getProductOfferReferencesByMerchantAndSku(
        array $bundledItemTransfers,
        array $merchantReferencesByBundleItemIdentifier,
    ): array {
        $skus = [];
        $merchantReferences = [];
        foreach ($bundledItemTransfers as $itemTransfer) {
            $skus[] = $itemTransfer->getSkuOrFail();
            $merchantReferences[] = $merchantReferencesByBundleItemIdentifier[$itemTransfer->getRelatedBundleItemIdentifierOrFail()];
        }

        $productOfferCriteriaTransfer = (new ProductOfferCriteriaTransfer())
            ->setConcreteSkus(array_values(array_unique($skus)))
            ->setMerchantReferences(array_values(array_unique($merchantReferences)))
            ->setIsActive(true)
            ->setApprovalStatuses([ProductOfferConfig::STATUS_APPROVED]);

        $productOfferReferencesByMerchantAndSku = [];
        foreach ($this->productOfferFacade->get($productOfferCriteriaTransfer)->getProductOffers() as $productOfferTransfer) {
            $merchantReference = $productOfferTransfer->getMerchantReferenceOrFail();
            $sku = $productOfferTransfer->getConcreteSkuOrFail();

            if (isset($productOfferReferencesByMerchantAndSku[$merchantReference][$sku])) {
                continue;
            }

            $productOfferReferencesByMerchantAndSku[$merchantReference][$sku] = $productOfferTransfer->getProductOfferReferenceOrFail();
        }

        return $productOfferReferencesByMerchantAndSku;
    }
}
